# ../aintegrator/integrator/src/profiles/db_model.py
import json
import logging
from sqlalchemy import Column, Text, ForeignKey, Boolean, DateTime, Index, text, Integer, String, BigInteger, ARRAY
from sqlalchemy.dialects.postgresql import UUID, JSONB
from pgvector.sqlalchemy import Vector
from sqlalchemy.orm import relationship, Session, backref
from sqlalchemy.sql import func
from sqlalchemy.schema import UniqueConstraint, ForeignKeyConstraint
from integrator.utils.crypto_utils import decrypt

from sqlalchemy.ext.declarative import declarative_base

# Import Domain model and Base from domain_db_model to ensure same Base is used
from integrator.domains.domain_db_model import Base, Domain

logger = logging.getLogger(__name__)


class Tenant(Base):
    __tablename__ = "tenants"

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    name = Column(Text, unique=True, nullable=False)
    description = Column(Text, nullable=True)
    # svc_inputs = Column(JSONB, nullable=False)  # Removed as app_keys table handles this
    created_at = Column(DateTime(timezone=True), server_default=func.now())



class Agent(Base):
    __tablename__ = "agents"

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    agent_id = Column(Text, nullable=False)  # This is the Keycloak client_id
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False)
    name = Column(Text, nullable=True)
    encrypted_secret = Column(Text, nullable=True)
    iv = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    tenant = relationship(Tenant) # Relationship to the tenant
    
    __table_args__ = (
        UniqueConstraint('agent_id', 'tenant_name', name='agents_agent_id_tenant_name_key'),
    )


class AgentProfile(Base):
    __tablename__ = "agent_profile"

    agent_id = Column(Text, nullable=False, primary_key=True)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False, primary_key=True)
    context = Column(JSONB, nullable=True)  # JSON filter configuration for agent capabilities
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationship to the agent
    __table_args__ = (
        ForeignKeyConstraint(
            ['agent_id', 'tenant_name'],
            ['agents.agent_id', 'agents.tenant_name'],
            ondelete="CASCADE",
            name='agent_profile_agent_id_tenant_name_fkey'
        ),
    )



class User(Base):
    __tablename__ = "users"

    # Keycloak user ID (sub) - Provided externally, not auto-generated by this DB
    id = Column(UUID(as_uuid=True), primary_key=True)
    username = Column(Text, nullable=False)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False)
    email = Column(Text, nullable=True)
    encrypted_credentials = Column(Text, nullable=True)
    iv = Column(Text, nullable=True)

    tenant = relationship(Tenant) # Relationship to the tenant
    
    __table_args__ = (
        UniqueConstraint('username', 'tenant_name', name='users_username_tenant_name_key'),
    )



class Role(Base):
    __tablename__ = "roles"
    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    name = Column(String(255), nullable=False)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False)
    type = Column(String(50), nullable=True)
    label = Column(String(255), nullable=False)
    description = Column(Text, default="")
    job_roles = Column(JSONB, nullable=True)
    constraints = Column(Text, nullable=True)
    emb = Column(Vector(1536), nullable=True)
    
    __table_args__ = (
        UniqueConstraint('name', 'tenant_name', name='roles_name_tenant_name_key'),
    )


class RoleUser(Base):
    __tablename__ = "role_user"
    role_name = Column(String, nullable=False, primary_key=True)
    username = Column(String, nullable=False, primary_key=True)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False, primary_key=True)
    
    __table_args__ = (
        ForeignKeyConstraint(
            ['role_name', 'tenant_name'],
            ['roles.name', 'roles.tenant_name'],
            ondelete="CASCADE",
            name='role_user_role_name_tenant_name_fkey'
        ),
        ForeignKeyConstraint(
            ['username', 'tenant_name'],
            ['users.username', 'users.tenant_name'],
            ondelete="CASCADE",
            name='role_user_username_tenant_name_fkey'
        ),
    )

class RoleAgent(Base):
    __tablename__ = "role_agent"
    role_name = Column(String, nullable=False, primary_key=True)
    agent_id = Column(String, nullable=False, primary_key=True)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False, primary_key=True)
    
    __table_args__ = (
        ForeignKeyConstraint(
            ['role_name', 'tenant_name'],
            ['roles.name', 'roles.tenant_name'],
            ondelete="CASCADE",
            name='role_agent_role_name_tenant_name_fkey'
        ),
        ForeignKeyConstraint(
            ['agent_id', 'tenant_name'],
            ['agents.agent_id', 'agents.tenant_name'],
            ondelete="CASCADE",
            name='role_agent_agent_id_tenant_name_fkey'
        ),
    )


class UserAgent(Base):
    """Relationship mapping between users and agents.
    
    This ORM class maps users to agents via the `user_agent` table,
    representing which agents a user has access to or manages.
    """
    __tablename__ = "user_agent"
    username = Column(String, nullable=False, primary_key=True)
    agent_id = Column(String, nullable=False, primary_key=True)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False, primary_key=True)
    role = Column(Text, nullable=True)
    context = Column(JSONB, nullable=True)
    
    __table_args__ = (
        ForeignKeyConstraint(
            ['username', 'tenant_name'],
            ['users.username', 'users.tenant_name'],
            ondelete="CASCADE",
            name='user_agent_username_tenant_name_fkey'
        ),
        ForeignKeyConstraint(
            ['agent_id', 'tenant_name'],
            ['agents.agent_id', 'agents.tenant_name'],
            ondelete="CASCADE",
            name='user_agent_agent_id_tenant_name_fkey'
        ),
    )


class RoleDomain(Base):
    """IAM relationship mapping between roles and domains.

    This ORM class maps roles to domains via the `role_domain` table, which
    uses `domain_name` as the foreign key to `domains.name`.
    """
    __tablename__ = "role_domain"
    role_name = Column(String, nullable=False, primary_key=True)
    domain_name = Column(String, nullable=False, primary_key=True)
    tenant_name = Column(Text, ForeignKey("tenants.name", ondelete="CASCADE"), nullable=False, primary_key=True)
    
    __table_args__ = (
        ForeignKeyConstraint(
            ['role_name', 'tenant_name'],
            ['roles.name', 'roles.tenant_name'],
            ondelete="CASCADE",
            name='role_domain_role_name_tenant_name_fkey'
        ),
        ForeignKeyConstraint(
            ['domain_name', 'tenant_name'],
            ['domains.name', 'domains.tenant_name'],
            ondelete="CASCADE",
            name='role_domain_domain_name_tenant_name_fkey'
        ),
    )



# Removed AgentTenant and AgentProfile as they are not in create_tables.sh or insert_tables.py logic

class AuthProvider(Base):
    __tablename__ = "auth_providers" # As requested

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    tenant_name = Column(Text, ForeignKey(Tenant.name, ondelete="CASCADE"), nullable=False, index=True)
    provider_id = Column(Text, nullable=False)  # e.g., 'google', 'github'
    provider_name = Column(Text, nullable=False)  # Human-readable name
    provider_type = Column(Text, nullable=False)  # Provider type classification
    type = Column(Text, nullable=False)        # 'oauth', 'oidc', 'credentials'
    client_id = Column(Text, nullable=True)
    encrypted_secret = Column(Text, nullable=True) # Hex encoded ciphertext + tag
    iv = Column(Text, nullable=True)              # Hex encoded IV
    is_built_in = Column(Boolean, nullable=False, server_default='t')
    options = Column(JSONB, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    tenant = relationship(Tenant) # Relationship to the tenant

    __table_args__ = (
        UniqueConstraint('tenant_name', 'provider_id', name='uq_auth_provider_tenant_providerid'),
    )

    def __repr__(self):
        return f"<auth_providers(id={self.id}, tenant_name='{self.tenant_name}', provider_id='{self.provider_id}', provider_name='{self.provider_name}')>"


class ProviderToken(Base):
    __tablename__ = "provider_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    token = Column(JSONB, nullable=False)
    username = Column(Text, nullable=True) # username is optional
    agent_id = Column(Text, nullable=False) # agent_id is required
    tenant_name = Column(Text, ForeignKey(Tenant.name, ondelete="CASCADE"), nullable=False, index=True)
    provider_id = Column(Text, nullable=False, index=True) # Part of FK to auth_providers

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    tenant = relationship(Tenant)
    # Relationship to AuthProvider using composite foreign key
    auth_provider = relationship(
        AuthProvider,
        foreign_keys=[tenant_name, provider_id],
        primaryjoin="and_(ProviderToken.tenant_name == AuthProvider.tenant_name, ProviderToken.provider_id == AuthProvider.provider_id)",
        backref=backref("provider_tokens", overlaps="tenant"), # adds 'provider_tokens' collection to AuthProvider
        overlaps="tenant"
    )


    __table_args__ = (
        UniqueConstraint('provider_id', 'agent_id', 'tenant_name', name='uq_provider_agent_tenant'),
        ForeignKeyConstraint(
            ['tenant_name', 'provider_id'],
            ['auth_providers.tenant_name', 'auth_providers.provider_id'],
            ondelete="CASCADE",
            name='fk_pt_auth_provider' # Naming the FK constraint explicitly in the model
        ),
        # Index for faster lookups on tenant_name and provider_id if not covered by FK
        Index('idx_pt_tenant_provider', 'tenant_name', 'provider_id'),
    )

    def __repr__(self):
        return f"<ProviderToken(id={self.id}, tenant_name='{self.tenant_name}', provider_id='{self.provider_id}', username='{self.username}', agent_id='{self.agent_id}')>"




def get_user_with_decrypted_credentials(db: Session, username: str) -> User | None:
    """
    Retrieves a user by username with credentials decrypted.

    Args:
        db: The database session.
        username: The username to search for.

    Returns:
        The User object with decrypted credentials, or None if not found.
    """
    user = db.query(User).filter(User.username == username).first()
    if not user:
        return None

    if user.encrypted_credentials and user.iv:
        try:
            decrypted_json = decrypt(user.encrypted_credentials, user.iv)
            user.credentials = json.loads(decrypted_json)
        except Exception as e:
            logger.warning(f"Could not decrypt credentials for user '{username}': {e}")
            user.credentials = None
    else:
        user.credentials = None

    return user
